# Global settings
[settings]
alive_seconds = 10

# Service definitions
[[services]]
name        = "postgres"
host        = "127.0.0.1"
port        = 5432
exposedPort = 5433

[[services]]
name        = "Website"
host        = "127.0.0.1"
port        = 3000
exposedPort = 3001
dependencies = ["postgres"]

[[services]]
name        = "Admin"
host        = "127.0.0.1"
port        = 4000
exposedPort = 4001
dependencies = ["postgres", "Website"]
